# Generated by Django 6.0 on 2026-02-12 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('reviewed', 'Рассмотрен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения статуса')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил статус')),
            ],
            options={
                'verbose_name': 'обращение обратной связи',
                'verbose_name_plural': 'обращения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
    ]
