# Generated by Django 6.0 on 2026-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='message',
            field=models.TextField(default='', verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
    ]
