# Generated by Django 6.0 on 2026-02-13 21:33

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentrequest_message_studentrequest_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='thread_opened_at',
            field=models.DateTimeField(blank=True, help_text='Когда куратор написал первое сообщение в переписке', null=True, verbose_name='Переписка открыта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Куратор'), ('student', 'Студент')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='Куратор (получатель)'),
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.request_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.studentrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'вложение заявки',
                'verbose_name_plural': 'вложения заявок',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='app.studentrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'сообщение в переписке',
                'verbose_name_plural': 'сообщения в переписке',
                'ordering': ['created_at'],
            },
        ),
    ]
