# Generated by Django 6.0 on 2026-02-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_studentrequest_thread_opened_at_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='request_type',
            field=models.CharField(blank=True, help_text='Отображается в выборе куратора у студентов (например: «Консультация по диплому»)', max_length=200, verbose_name='Тип запроса'),
        ),
    ]
